import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Providers } from "@/queries/providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Axiom SOL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.variable} bg-[#0b0c10] text-1 h-full font-inter antialiased overflow-hidden`}
      >
        <Providers>
          {/* NAVBAR  */}
          <header className="fixed top-0 left-0 right-0 z-50">
            <Navbar />
          </header>

          {/* MAIN CONTENT */}
          <main
            className="
              absolute left-0 right-0
              overflow-x-hidden

              /* Mobile navbar/footer sizes */
              top-[50px] bottom-[50px]

              /* Tablet > */
              sm:top-[70px] sm:bottom-[55px]

              /* Desktop > */
              lg:top-[80px] lg:bottom-[60px]

              /* XL > */
              xl:top-[90px] xl:bottom-[25px]
            "
          >
            {children}
          </main>

          {/*  FOOTER */}
          <footer className="fixed bottom-0 left-0 right-0 z-50">
            <Footer />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
